version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - add_ssh_keys:
          fingerprints:
            - "64:ed:07:d3:f9:7e:42:af:74:25:b0:f1:91:26:47:f2"

      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      
      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: app/build/reports
          destination: reports

      - run:
          name: Build apk
          command: ./gradlew :app:assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk  # debug -> from app:assembleDebug
          destination: app-debug.apk
      
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      
      - persist_to_workspace:
          root: app/build/outputs/apk/
          paths:
            - debug


  deploy:
    working_directory: app/build/outputs/apk/
    docker:
      - image: circleci/python:3.6.4
    steps:
      - attach_workspace:
          at: app/build/outputs/apk/
      #- checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync ./app-debug.apk s3://tech-book-review-site --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
	    - build
	  filters:
	    branches:
	      only: master
        